@extends('layout')
@section('title')
    <title>Terms & Conditions</title>
@endsection
@section('meta')
    <meta name="description" content="Terms & Conditions">
@endsection
@section('public-content')
    <!--============================
        CUSTOM PAGES PAGE START
    ==============================-->
    <section id="wsus__product_page" class="dynamic-pg py-5">
        <div class="container">
            <div class="position-relative">
                <img src="{{ asset('public/uploads/website-images/images/terms-conditions.png') }}" class="w-100 banner-img">
                <div class="position-absolute banner-section">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb mb-0">
                            <li class="breadcrumb-item">Home</li>
                            <li class="breadcrumb-item" aria-current="page">Policy</li>
                            <li class="breadcrumb-item active" aria-current="page">Terms and Conditions</li>
                        </ol>
                    </nav>
                    <h1 class="heading">Terms and Conditions for eIndustrify</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-xl-12">
                    <div class="text-end my-4">
                        <a href="" class="text-underline red-link">Download</a>
                    </div>
                    <h4>Terms and Conditions</h4>
                    <p class="mt-4">Last updated: March 10, 2023</p>
                    <p class="mb-4">Please read these terms of registerations carefully before using Our Service.</p>
                    <b class="d-block mb-4">Welcome</b>
                    <p>Welcome to the EIndustrify.com website and mobile application owned and operated by W.W. EIndustrify, Inc. (“EIndustrify,” “we” or “us”). The EIndustrify.com website and mobile application, together with the content, software, services, and functionality offered on or through the website and mobile application, are collectively referred to as the “EIndustrify Property” in these Terms of Access. The EIndustrify Property offers industrial supplies and safety products to help keep your business running. We make the EIndustrify Property available to you subject to your agreement to these Terms of Access. The purchase of products and services available through the EIndustrify Property is subject to additional terms and policies. You should review those terms and policies before making a purchase. These Terms of Access (including all documents, policies, conditions and notices) referenced in these Terms of Access) are collectively referred to as the “Agreement.” In this Agreement, the words “include” and “including” will not be construed as terms of limitation. The Agreement is a legally binding contract between you and EIndustrify. By accessing the EIndustrify Property in any way, including, without limitation, browsing the EIndustrify Property, using any information contained on or in the EIndustrify Property, creating a User Account (defined below), and/or submitting information to EIndustrify, you agree to and are bound by this Agreement, including, but not limited to, conducting transactions electronically, disclaimers of warranties, damage and remedy exclusions and limitations, and a choice of Illinois law. Our collection and use of personal information in connection with your access to and use of the EIndustrify Property, whether or not you are a registered user, is described in our Privacy Policy</p>
                    <h6 class="my-4">-----</h6>
                    <b class="d-block">1. Updates to the Agreement</b>
                    <p class="mb-4">From time to time, EIndustrify may update the Agreement. If we materially update any portion of the Agreement, we will notify you by posting a revised Agreement through the mobile app or a notice on our website before the date the update becomes effective. We will also post the updated Agreement in its original location marked with the new date. Changes will not be retroactive. If you object to any changes, you should not access or use the EIndustrify Property. Your continued access or use of the EIndustrify Property after we publish our changes to the Agreement means that you are consenting to the updated terms.</p>
                    <p>By accessing or linking to the EIndustrify Property, you assume the risk that the information on the EIndustrify Property may be incomplete, inaccurate, or out of date, or may not meet your needs and requirements. EIndustrify may add, change, discontinue, remove or suspend any of the information, features and other content included in the EIndustrify Property at any time, without notice and without liability. Due to the open nature of the EIndustrify Property, and the potential for errors in the storage and transmission of digital information, EIndustrify does not warrant the accuracy of information contained on or obtained from the EIndustrify Property.</p>
                    <b class="d-block mt-4">2. EIndustrify Property</b>
                    <p>A. Your Right to Use EIndustrify Property</p>
                    <p>EIndustrify grants you a limited, non-exclusive, non-transferable, non-assignable, non-sublicensable, fully revocable license to access and make use of the EIndustrify Property solely for legitimate non-commercial, business purposes, and as permitted by the features and functionalities of the EIndustrify Property, subject to this Agreement. Any access or attempt to access other areas of EIndustrify Property or any EIndustrify systems or other information contained on EIndustrify Property or EIndustrify systems for any other purposes is strictly prohibited. You will not (i) remove or modify any copyright, trademark or other proprietary rights notice that appears on any portion of the EIndustrify Property, or on any materials printed or copied from the EIndustrify Property; or (ii) dilute, tarnish or otherwise harm our brand in any way, including through unauthorized use of EIndustrify Property, registering and/or using EIndustrify or derivative terms in domain names, trade names, trademarks or other source identifiers, or registering and/or using domains names, trade names, trademarks or other source identifiers that closely imitate or are confusingly similar to EIndustrify domains, trademarks, taglines, promotional campaigns or EIndustrify Content.</p>
                    <b class="d-block">B. Eligibility</b>
                    <p>You may use the EIndustrify Property only if you can form a binding contract with EIndustrify, and only in compliance with this Agreement and all applicable local, state, national, and international laws, rules and regulations. Any use or access to the EIndustrify Property by anyone under eighteen (18) years of age is strictly prohibited and in violation of this Agreement.</p>
                    <b class="d-block">C. User Accounts</b>
                    <p>In order to use certain features on the EIndustrify Property, such as viewing your past orders or saved searches, you may need to register and create an account on the EIndustrify Property (your “User Account”). You should not use another user’s User Account without permission. When creating your User Account, you must provide accurate and complete information, and you must keep this information up to date. You are solely responsible for the activity that occurs on your User Account, and you must keep your User Account password secure. We encourage you to use “strong” passwords (a password that is unique to the account, is 16 or more characters or a passphrase) with your User Account. If we determine that your password is unsafe, we may notify you and recommend you use a different strong password. If you use a weak password or one we identify as unsafe, you accept all liability and risk if someone uses that password to access your account without your authorization. You must notify EIndustrify immediately of any breach of security or unauthorized use of your User Account. EIndustrify will not be liable for any losses caused by any unauthorized use of your User Account. By providing EIndustrify your email address you consent to our using the email address to send you service-related notices relating to the EIndustrify Property, including any notices required by law or regarding updates to the Agreement, in lieu of communication by postal mail. We may also use your email address to send you other messages, such as changes to features of the EIndustrify Property and, depending on where you are resident, special offers. If you do not want to receive such email messages, you may opt out or change your preferences by Email Preference Link.</p>
                    <b class="d-block">D. Availability of EIndustrify Property</b>
                    <p>Due to the nature of the Internet, we cannot guarantee the continuous and uninterrupted availability of any portion of the EIndustrify Property and are not responsible for outages or disruptions of the Internet and telecommunications infrastructure which are beyond our control. We may temporarily restrict the availability of the EIndustrify Property or certain areas or features thereof with or without notice. We may from time to time change, discontinue, enhance and modify the EIndustrify Property and introduce new features or functionality from time to time. You agree that you do not have any rights in the EIndustrify Property and that EIndustrify will have no liability to you if the EIndustrify Property is discontinued or your ability to access the EIndustrify Property or any content you may have posted on the EIndustrify Property is terminated.</p>
                    <b class="d-block">E. Hypertext Links</b>
                    <p>The EIndustrify Property may be linked to other sites that are not maintained by EIndustrify. EIndustrify is not responsible for the content of or privacy or other policies governing those sites. The inclusion of any link to such sites does not imply endorsement, sponsorship, or recommendation by EIndustrify of the linked sites. EIndustrify disclaims any and all liability for links: (i) from another site to the EIndustrify Property, and (ii) to another site from the EIndustrify Property. In order to link to the EIndustrify Property all users must comply with the EIndustrify Linking Terms.</p>
                    <b class="d-block">F. Visual and Barcode Search</b>
                    <p>EIndustrify may, from time to time, make available a functionality through the EIndustrify Property that allows you to upload images and barcodes to the EIndustrify Property and that analyzes such images in order to search for and return suggested products available through the EIndustrify Property that match those images and barcodes ("Visual Search"). In order to use Visual Search, you will need to download our mobile application onto your device and allow the application to access the camera on your device. You must ensure that all images you upload through Visual Search comply with the paragraph below headed "Uploading Images, Reviews and other Content". We reserve the right to suspend your access to Visual Search or the EIndustrify Property if you breach the Agreement.</p>
                    <b class="d-block">G. Chat functionality</b>
                    <p>EIndustrify may make available certain messaging features through the EIndustrify Property that allow you to message and share content with a customer service representative in real time (the "Messaging Service"). In addition to any other requirements in the Agreement, when using the Messaging Service, you must ensure that any messages, images or other content that you upload to the Messaging Service comply with the paragraph below headed "Uploading Images, Reviews and other Content" and you must not: (i) threaten or abuse any customer service representative through the Messaging Service, or abuse or invade another person's privacy, or cause annoyance, inconvenience or needless anxiety, or do anything through the Messaging Service that is likely to harass, upset, embarrass, alarm or annoy any other person; (ii) advocate, promote or engage in any illegal or unlawful conduct, including any criminal activity, fraud or money laundering, or conduct that causes damage or injury to any person or property; (iii) promote or advertise any goods or services or send any unsolicited marketing communications through the Messaging Service. Failure to comply with the above paragraph may result in us immediately suspending or terminating your access to the Messaging Service and/or the EIndustrify Property; issuing a warning to you; taking legal action against you (including proceedings for reimbursements of all costs, including reasonable administrative and legal costs, that we incur as a result of your breach); disclosing such information to law enforcement authorities as we reasonably believe is necessary; and taking any other steps that we reasonably deem appropriate.</p>
                    <b class="d-block">H. Accessibility</b>
                    <p>W.W. EIndustrify, Inc. is committed to accessibility, diversity and inclusion for all of its guests. We believe everyone should be able to easily shop online at www.eIndustrify.com, use our mobile app and access our services easily. We set high standards for web accessibility and constantly strive to ensure we’re in compliance with all laws and guidelines. Our team is filled with professionals who are dedicated to making your online experiences the best they can be. We welcome feedback from guest experiences. If you have any questions about our accessibility features, please contact us at 1-800-472-4643 or accessibility@eIndustrify.com.</p>
                    <b class="d-block">I. Promotions</b>
                    <p>Any sweepstakes, contests, raffles, surveys, games or similar promotions (collectively, “Promotions”) made available through the EIndustrify Property may be governed by rules or terms that are separate from the Agreement. If you participate in any Promotions, please review the applicable rules or terms as well as our Privacy Policy. If the rules or terms for a Promotion conflict with the Agreement, the Promotion rules will govern.</p>
                    <b class="d-block mt-4">3. Use of and Responsibility for Content</b>
                    <b class="d-block">A. EIndustrify Content</b>
                    <p>Content on the EIndustrify Property that is provided by EIndustrify or its licensors, including software, graphics, photographs, images, screen shots, text, digitally downloadable files, trademarks, logos, product, service and program names, slogans, and the compilation of the foregoing ("EIndustrify Content") is the property of EIndustrify or its licensors, and is protected in the U.S. and internationally under trademark, copyright, and other intellectual property laws. Except as explicitly provided herein, nothing in the Agreement shall be deemed to create a license in or under any such intellectual property rights, and you agree not to sell, license download, screenshot, rent, modify, distribute, copy, reproduce, transmit, display to third parties, publicly perform, publish, adapt, edit or create derivative works from any EIndustrify Content.</p>
                    <b class="d-block">B. Uploading Images, Reviews and other Content</b>
                    <p>From time to time on certain areas of the EIndustrify Property you may be able to submit or transmit to, though, or in connection with the EIndustrify Property any information (including personal information), text, links, graphics, photos, images, audio, videos, and all other forms of data or communication ("User Content"). By submitting or otherwise transmitting any User Content on or through the EIndustrify Property, you hereby grant to EIndustrify a limited, non-exclusive, sub-licensable, worldwide, fully-paid, royalty free license to use, modify, publicly perform, publicly display, reproduce, and distribute such User Content in any and all media now known or hereinafter developed without the requirement to make payment to you or to any third party or the need to seek any third-party permission. This license includes the right to host, index, cache, distribute, and tag any User Content, as well as the right to sublicense User Content to third parties (including other users), for use with marketing or on other media or platforms known or hereinafter developed. With regard to the Visual Search (described above), this license additionally includes the right to use the images you upload to enhance and continually improve our visual search algorithm and functionality. Insofar as User Content includes personal information, including. but not limited to, images or photographs of individuals, you agree that such personal information will be used or disclosed for these purposes. EIndustrify does not guarantee any confidentiality with respect to any of your User Content. You continue to retain all ownership rights in your User Content, and you continue to have the right to use your User Content in any way you choose, subject to this Agreement and the license described herein. You represent and warrant that you own or have a valid license to use and provide to EIndustrify the User Content submitted, displayed, published or posted by you on the EIndustrify Property and otherwise have the right (including the necessary licenses and/or permissions from third parties) to grant the license set forth herein, and the displaying, publishing or posting of any content you submit, and EIndustrify’s use thereof does not and will not violate the privacy rights, publicity rights, copyrights, trademark rights, patents, contract rights or any other intellectual property rights or other rights of any person or entity.</p>
                    <b class="d-block">C. Third-Party Technology, Websites and Applications</b>
                    <p>The EIndustrify Property may include third-party technology, services, software, applications, and links to third-party websites (“Technology”). EIndustrify is not responsible for the practices or policies of such third parties, nor the content of any third-party website or application, and does not make any representation regarding third-party product or Technology, or content or accuracy of any material on such websites or applications. If you decide to use any such third-party website or application, you do so at your own risk. To the extent applicable, your use of such third-party Technology is subject to this Agreement as well as the additional terms and conditions as EIndustrify may provide to you from time to time.</p>
                    <b class="d-block mt-4">4. Information and Complaints</b>
                    <p>If you have a question or complaint regarding the EIndustrify Property, please send an e-mail to ipcomplaints@eIndustrify.com. You may also contact EIndustrify by phone or mail at the contact information provided on the EIndustrify Property. Please note that e-mail communications will not necessarily be secure; accordingly you should not include credit card information or other sensitive information, including sensitive personal information or health information, in your e-mail correspondence with EIndustrify. California residents may reach the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by mail at 1625 North Market Blvd., Sacramento, CA 95834, or by telephone at (916) 445-1254 or (800) 952-5210.</p>
                    <b class="d-block mt-4">5. Miscellaneous</b>
                    <p>The Agreement will be governed by and construed in accordance with the laws of Illinois without regard to conflicts of laws principles. By using the EIndustrify Property, you hereby agree that any and all disputes regarding the Agreement will be subject to the courts located in Lake County, Illinois or the federal courts for the Northern District of Illinois. The Agreement operates to the fullest extent permissible by law. Accessing materials on the EIndustrify Property by certain persons in certain countries may not be lawful, and EIndustrify makes no representation that materials on the EIndustrify Property are appropriate or available for use in locations outside the United States. If you choose to access the EIndustrify Property from outside the United States, you do so at your own risk and initiative, and are responsible for compliance with any applicable local laws.</p>
                    <p>If EIndustrify fails to act with respect to your breach or anyone else's breach on any occasion, EIndustrify is not waiving its right to act with respect to future or similar breaches.</p>
                    <p>If any provision of the Agreement shall be unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from the Agreement and shall not affect the validity and enforceability of any remaining provisions of this Agreement.</p>
                </div>
            </div>
        </div>
    </section>
    <!--============================
        CUSTOM PAGES PAGE END
    ==============================-->
@endsection
